Admin
Open-Quran-Learning/Website pull request #47
Opened 2020-04-29 21:53 UTC by AbdelrahmanElsemary

the login page component will be the same for students and admins(staff) but we'll control it's route and where it appears for student and where for admins,
this is the registration for admin will appear for admins only as behind the scene of the user this page will send type:"STAFF" to the API so his request will be treated as staff and the back-end will decide his position (supervisor - teacher- page admin "whatever as the database leader required")

2020-04-30 14:26 UTC, HazemGabr232 requested changes

2020-04-30 14:26 UTC, HazemGabr232 commented on src/components/Login/LoginComponent.jsx
> +            .then(response => {
Use ayat api also here

2020-04-30 14:26 UTC, HazemGabr232 commented on src/components/Login/LoginComponent.jsx
> +                console.log(`statusCode: ${res.statusCode}`)
Use ayat api here

2020-04-30 17:20 UTC, AbdelrahmanElsemary reviewed
the login page component will be the same for students and admins(staff) but we'll control it's route and where it appears for student and where for admins,
this is the registration for admin will appear for admins only as behind the scene of the user this page will send type:"STAFF" to the API so his request will be treated as staff and the back-end will decide his position (supervisor - teacher- page admin "whatever as the database leader required")
________________________________________________________
i changed the api from the fake one to ayat api

2020-05-01 14:14 UTC, HazemGabr232 approved these changes

2020-05-01 14:14 UTC, merged